export const MAKRO_CATEGORIES_MS = 'http://makro-category-api.dev:8046'
export const CDN_API_URL = 'http://alpha-api-makro-cdn.eggdigital.com'
export const CDN_PRIVATE_KEY = 'eb38bc90bedd71fa058cc51b71d3965e'
export const CDN_SERVICE_NAME = 'Makro'
export const CDN_SERVICE_ID = '1'
